name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build & push the docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    - name: set up kubectl
      uses: matootie/dokube@v1.3.4
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: k8s-customer-debts

    - name: kubectl get nodes
      run: kubectl get nodes
