name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check Changes
      id: changes
      run: |
        # Obtener la lista de archivos modificados
        archivos_modificados=$(git diff --name-only -r HEAD^1 HEAD)

        # Mostrar la lista de archivos modificados
        echo "Archivos modificados:"
        echo "$archivos_modificados"

        # Validar si hay cambios en una carpeta específica
        if echo "$archivos_modificados" | grep -q "cloudformation"; then
          echo "Se realizaron cambios en la carpeta especificada."
        else
          echo "No hay cambios en la carpeta especificada."
        fi

    - name: Validate Changes
      if: steps.changes.outputs.run_job == 'true'
      id: validate
      run: |
        echo "Changes!!!"

